name: Benchmark CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Install dependencies
      run: sudo apt-get install -y sbcl perl6 nim
    - name: Run the bench script
      run: ./bench.sh
