name: Benchmark CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      lang:
        description: 'Language to run'
        required: false

jobs:
  benchmark:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - uses: actions/setup-elixir@v1.2.0
      with:
        otp-version: '22.x'
        elixir-version: '1.9.x'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.5.x'
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.6'
    - name: Install dependencies
      run: ./install.sh
    - name: Run the bench script
      run: ./bench.py ${{ github.event.inputs.lang }}
