name: Benchmark CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - uses: actions/setup-elixir@v1.2.0
      with:
        otp-version: '22.x'
        elixir-version: '1.9.x'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.5.x'
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.6'
    - name: Install dependencies
      run: |
        sudo apt-get install -y sbcl perl6 nim php-gmp
        pip3 install -r requirements.txt
        curl -O http://www.jsoftware.com/download/j902/install/j902_linux64.tar.gz
        tar xf j902_linux64.tar.gz &&
          sudo mv j902 /usr/local/share &&
          sudo ln -sf /usr/local/share/j902/bin/jconsole /usr/local/bin/jcons
    - name: Run the bench script
      run: ./bench.py
