name: Benchmark CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      lang:
        description: 'Language to run'
        required: false

jobs:
  benchmark:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '24.0.2'
        elixir-version: '1.12.1'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.5.x'
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.6'
    - name: Install dependencies
      run: ./install.sh
    - name: Run the bench script
      run: ./bench.py ${{ github.event.inputs.lang }}
